[package]
name = "quests_system"
version = "0.1.0"
edition = "2021"

[dependencies]
quests_db = { path = "../db" }
quests_message_broker = { path = "../message_broker" }
quests_definitions = { path = "../definitions" }
serde = { workspace = true }
serde_json = { workspace = true }
config = { workspace = true }
log = { workspace = true }
tokio = { version = "1", features = ["full"] }
bincode = "1.3.3"
