[workspace]
members=["crates/*"]

[workspace.dependencies]
sqlx = { version = "0.6", features = [ "runtime-actix-native-tls" , "postgres", "uuid", "json", "chrono" ] }
log = "0.4.16"
env_logger = "0.9.0"
config = "0.13"
serde = "1"
serde_json = "1"
