version: "3.8"
services:
  postgres:
    container_name: "quests_db"
    image: "postgres:latest"
    restart: always
    user: postgres
    volumes:
      - quests_db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quests_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    container_name: "quests_redis"
    image: "redis:latest"
    restart: always
    user: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
  server:
    build:
      context: .
      args:
        PROJECT: quests_server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:postgres@quests_db:5432/quests_db
      - REDIS_URL=quests_redis:6379
    depends_on:
      - postgres
      - redis
  system:
    build:
      context: .
      args:
        PROJECT: quests_system
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@quests_db:5432/quests_db
      - REDIS_URL=quests_redis:6379

volumes:
  quests_db_volume:
