version: '3.8'
services:
  postgres:
    container_name: "quests_db"
    image: 'postgres:latest'
    restart: always
    user: postgres
    volumes:
      - quests_db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quests_db
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    container_name: "quests_redis"
    image: 'redis:latest'
    restart: always
    user: redis
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
  server:
    build: 
      context: .
      dockerfile: server.dockerfile
    ports: 
      - "8080:8080"
    restart: always
    depends_on:
      - postgres 
      - redis 
  system:
    build:
      context: .
      dockerfile: system.dockerfile
    restart: always
    depends_on:
      - postgres
      - redis 

volumes:
  quests_db_volume:
