pub mod quests;

pub mod definitions {
    pub use prost::DecodeError as ProtocolDecodeError;
    pub use prost::Message as ProtocolMessage;

    // Includes the autogenerated types defined in the .proto
    include!(concat!(env!("OUT_DIR"), "/decentraland.quests.rs"));
}

pub mod rewards;
