[package]
name = "quests_db_sqlx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quests_db_core = { path = "../db_core" }
async-trait = "0.1.61"
sqlx.workspace = true
