[package]
name = "quests_db_core"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.61"
serde = { version = "1.0.152", features = ["derive"] }
thiserror = "1.0.38"

[features]
default = []
test = []