on: [pull_request]
name: Clippy check
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Clippy
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - name: Running Clippy
        working-directory: ./crates
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features