name: Publish Latest Docker image

on:
  release:
    types: [published]
  push:
    branches: [main, chore/pre-fetch] # remove new branch before merge

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - run: cargo fetch
  publish_server:
    needs: fetch
    uses: decentraland/actions/.github/workflows/build-quay-main.yml@main
    with:
      service-name: quests-server
      build-args: PROJECT=quests_server
      layers: true
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
  publish_system:
    needs: fetch
    uses: decentraland/actions/.github/workflows/build-quay-main.yml@main
    with:
      service-name: quests-system
      build-args: PROJECT=quests_system
      layers: true
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
