name: Publish Latest Docker image

on:
  release:
    types: [published]
  push:
    branches: [main]

jobs:
  push-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          shared-key: main
          key: build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Build and push (quests server)
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: quay.io/decentraland/quests-server:latest,quay.io/decentraland/quests-server:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PROJECT=quests_server
